'use client';
/* eslint-disable @next/next/no-html-link-for-pages */
import {FormEvent,useCallback,useEffect,useMemo,useState} from 'react';

type Operation={id:string;record_type:string;title:string;description:string;category:string;location:string;contact_name:string;contact_email:string;contact_phone:string;priority:string;status:string;latitude:number|null;longitude:number|null;people_count:number;source:string;created_by:string;created_at:string;updated_at:string;published_at:string|null};
type Audit={id:string;record_id:string;action:string;actor_email:string;created_at:string};
type Count={record_type:string;status:string;count:number};
const modules=[['overview','⌂','Command center'],['request','✚','Help requests'],['offer','♡','Offers & volunteers'],['reunification','♟','Family reunification'],['map','⌖','Map & locations'],['update','◉','Situation reports'],['organization','◆','Organizations'],['alert','!','Emergency alerts'],['stories','▤','Human stories'],['settings','⚙','System health']];
const labels:Record<string,string>={request:'Help request',offer:'Offer / volunteer',reunification:'Family case',map:'Map location',update:'Situation report',organization:'Organization',alert:'Emergency alert'};
const emptyForm={record_type:'request',title:'',description:'',category:'',location:'',contact_name:'',contact_email:'',contact_phone:'',priority:'medium',status:'draft',latitude:'',longitude:'',people_count:'0',source:''};

export default function AdminConsole({adminEmail}:{adminEmail:string}){
  const [module,setModule]=useState('overview'),[records,setRecords]=useState<Operation[]>([]),[counts,setCounts]=useState<Count[]>([]),[storyCounts,setStoryCounts]=useState<Array<{status:string;count:number}>>([]),[recent,setRecent]=useState<Audit[]>([]),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[statusFilter,setStatusFilter]=useState('all'),[showForm,setShowForm]=useState(false),[form,setForm]=useState({...emptyForm}),[notice,setNotice]=useState(''),[mobileNav,setMobileNav]=useState(false);
  const load=useCallback(async()=>{setLoading(true);const response=await fetch('/api/admin/operations');if(response.ok){const data=await response.json() as {records:Operation[];counts:Count[];storyCounts:Array<{status:string;count:number}>;recent:Audit[]};setRecords(data.records);setCounts(data.counts);setStoryCounts(data.storyCounts);setRecent(data.recent)}setLoading(false)},[]);
  useEffect(()=>{let active=true;fetch('/api/admin/operations').then(async response=>response.ok?await response.json() as {records:Operation[];counts:Count[];storyCounts:Array<{status:string;count:number}>;recent:Audit[]}:null).then(data=>{if(active&&data){setRecords(data.records);setCounts(data.counts);setStoryCounts(data.storyCounts);setRecent(data.recent)}if(active)setLoading(false)}).catch(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
  const visible=useMemo(()=>records.filter(r=>(module==='overview'||module==='settings'||module==='stories'||r.record_type===module)&&(statusFilter==='all'||r.status===statusFilter)&&(!search||`${r.title} ${r.location} ${r.description}`.toLowerCase().includes(search.toLowerCase()))),[records,module,statusFilter,search]);
  const count=(type?:string,status?:string)=>counts.filter(c=>(!type||c.record_type===type)&&(!status||c.status===status)).reduce((n,c)=>n+Number(c.count),0);
  const openNew=(type?:string)=>{setForm({...emptyForm,record_type:type&&labels[type]?type:'request'});setShowForm(true)};
  const submit=async(e:FormEvent)=>{e.preventDefault();setNotice('Saving record…');const response=await fetch('/api/admin/operations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(response.ok){setNotice('Record created.');setShowForm(false);await load()}else{const data=await response.json().catch(()=>({})) as {error?:string};setNotice(data.error||'Could not create record.')}};
  const update=async(id:string,status:string)=>{setNotice('Updating…');const response=await fetch('/api/admin/operations',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,status})});if(response.ok){setRecords(list=>list.map(r=>r.id===id?{...r,status,updated_at:new Date().toISOString()}:r));setNotice(`Record moved to ${status}.`)}else setNotice('Could not update record.')};
  const currentTitle=modules.find(m=>m[0]===module)?.[2]||'Command center';
  return <main className="admin-shell">
    <aside className={mobileNav?'admin-sidebar open':'admin-sidebar'}><div className="admin-brand"><span>♡</span><div><b>NRC CONTROL</b><small>NEPAL RELIEF CONNECT</small></div><button onClick={()=>setMobileNav(false)}>×</button></div><nav>{modules.map(([id,icon,label])=><button key={id} className={module===id?'active':''} onClick={()=>{setModule(id);setMobileNav(false)}}><i>{icon}</i><span>{label}</span>{!['overview','stories','settings'].includes(id)&&<em>{count(id)}</em>}{id==='stories'&&<em>{storyCounts.reduce((n,c)=>n+Number(c.count),0)}</em>}</button>)}</nav><div className="admin-user"><i>{adminEmail.slice(0,1).toUpperCase()}</i><span><b>Administrator</b><small>{adminEmail}</small></span><a href="/">↗</a></div></aside>
    <section className="admin-main"><header className="admin-top"><button className="mobile-menu" onClick={()=>setMobileNav(true)}>☰</button><div><small>OPERATIONS / {module.toUpperCase()}</small><h1>{currentTitle}</h1></div><div className="admin-top-actions"><label>⌕<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search records, locations…"/></label><button className="admin-new" onClick={()=>openNew(module)}>＋ NEW RECORD</button></div></header>
    <div className="admin-livebar"><span><i/> SYSTEM ONLINE</span><span>Verified data only</span><span>Last sync: just now</span><a href="/" target="_blank">VIEW PUBLIC SITE ↗</a></div>
    {notice&&<button className="admin-notice" onClick={()=>setNotice('')}>{notice}<span>×</span></button>}
    <div className="admin-content">{module==='overview'?<>
      <div className="metric-grid"><article><span className="metric-red">✚</span><div><small>ACTIVE REQUESTS</small><b>{count('request','published')+count('request','verified')}</b><em>{count('request','pending')} awaiting review</em></div></article><article><span className="metric-green">♡</span><div><small>AVAILABLE OFFERS</small><b>{count('offer','published')+count('offer','verified')}</b><em>{count('offer','pending')} awaiting review</em></div></article><article><span className="metric-purple">♟</span><div><small>FAMILY CASES</small><b>{count('reunification')}</b><em>{count('reunification','resolved')} resolved</em></div></article><article><span className="metric-blue">✓</span><div><small>PUBLISHED RECORDS</small><b>{count(undefined,'published')}</b><em>Visible to the public</em></div></article></div>
      <div className="admin-dashboard-grid"><section className="priority-panel"><div className="admin-section-head"><div><small>OPERATIONS</small><h2>Priority queue</h2></div><button onClick={()=>openNew()}>＋ Add record</button></div>{loading?<AdminLoader/>:<RecordsTable records={records.filter(r=>['critical','high'].includes(r.priority)&&!['resolved','archived'].includes(r.status)).slice(0,7)} update={update}/>}</section><section className="health-panel"><div className="admin-section-head"><div><small>DATA READINESS</small><h2>Public dashboard health</h2></div><b>{count(undefined,'published')?'LIVE':'PRE-LAUNCH'}</b></div>{[['Requests',count('request','published'),'red'],['Offers',count('offer','published'),'green'],['Map points',count('map','published'),'blue'],['Updates',count('update','published'),'orange'],['Organizations',count('organization','published'),'purple'],['Alerts',count('alert','published'),'red']].map(([name,value,color])=><div className="health-row" key={String(name)}><span><i className={`dot-${color}`}/>{name}</span><b>{value}</b><em>{Number(value)>0?'Connected':'Awaiting data'}</em></div>)}</section></div>
      <div className="admin-dashboard-grid lower"><section><div className="admin-section-head"><div><small>DATABASE</small><h2>All modules</h2></div></div><div className="module-cards">{modules.slice(1,8).map(([id,icon,label])=><button key={id} onClick={()=>setModule(id)}><i>{icon}</i><span><b>{label}</b><small>{count(id)} records</small></span><em>→</em></button>)}</div></section><section className="activity-panel"><div className="admin-section-head"><div><small>AUDIT TRAIL</small><h2>Recent activity</h2></div></div>{recent.length?recent.map(a=><div className="activity-row" key={a.id}><i>✓</i><span><b>{a.action}</b><small>{a.actor_email} · {new Date(a.created_at).toLocaleString()}</small></span></div>):<EmptyMini text="Activity will appear as records are created and reviewed."/>}</section></div>
    </>:module==='stories'?<StoryAdmin storyCounts={storyCounts}/>:module==='settings'?<SystemHealth counts={counts}/>:<section className="records-panel"><div className="records-toolbar"><div><button className={statusFilter==='all'?'active':''} onClick={()=>setStatusFilter('all')}>All <b>{records.filter(r=>r.record_type===module).length}</b></button>{['draft','pending','verified','published','resolved','archived'].map(s=><button key={s} className={statusFilter===s?'active':''} onClick={()=>setStatusFilter(s)}>{s} <b>{count(module,s)}</b></button>)}</div><button onClick={()=>openNew(module)}>＋ Add {labels[module]||'record'}</button></div>{loading?<AdminLoader/>:<RecordsTable records={visible} update={update}/>}</section>}</div></section>
    {showForm&&<div className="admin-modal"><form onSubmit={submit}><button type="button" className="admin-modal-close" onClick={()=>setShowForm(false)}>×</button><small>NEW OPERATIONAL RECORD</small><h2>Add to the command center</h2><p>Records stay private until they are verified and published.</p><div className="admin-form-grid"><label>Record type<select value={form.record_type} onChange={e=>setForm({...form,record_type:e.target.value})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option><option>critical</option></select></label><label className="wide">Title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label className="wide">Description<textarea rows={4} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Category<input value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label><label>Location<input value={form.location} onChange={e=>setForm({...form,location:e.target.value})}/></label><label>People affected / available<input type="number" min="0" value={form.people_count} onChange={e=>setForm({...form,people_count:e.target.value})}/></label><label>Source<input value={form.source} onChange={e=>setForm({...form,source:e.target.value})}/></label><label>Contact name<input value={form.contact_name} onChange={e=>setForm({...form,contact_name:e.target.value})}/></label><label>Contact email<input type="email" value={form.contact_email} onChange={e=>setForm({...form,contact_email:e.target.value})}/></label><label>Latitude<input type="number" step="any" value={form.latitude} onChange={e=>setForm({...form,latitude:e.target.value})}/></label><label>Longitude<input type="number" step="any" value={form.longitude} onChange={e=>setForm({...form,longitude:e.target.value})}/></label></div><div className="admin-form-actions"><button type="button" onClick={()=>setShowForm(false)}>Cancel</button><button type="submit">SAVE AS DRAFT</button></div></form></div>}
  </main>
}

function RecordsTable({records,update}:{records:Operation[];update:(id:string,status:string)=>void}){return records.length?<div className="admin-table"><div className="table-head"><span>Record</span><span>Location</span><span>Priority</span><span>Status</span><span>Updated</span><span>Action</span></div>{records.map(r=><div className="table-row" key={r.id}><span><i className={`type-${r.record_type}`}>{modules.find(m=>m[0]===r.record_type)?.[1]}</i><span><b>{r.title}</b><small>{labels[r.record_type]} · {r.category||'Uncategorized'}</small></span></span><span>{r.location||'—'}</span><span><b className={`priority-${r.priority}`}>{r.priority}</b></span><span><b className={`record-status status-${r.status}`}>{r.status}</b></span><span>{new Date(r.updated_at).toLocaleDateString()}</span><span><select value={r.status} onChange={e=>update(r.id,e.target.value)}>{['draft','pending','verified','published','resolved','archived'].map(s=><option key={s}>{s}</option>)}</select></span></div>)}</div>:<div className="admin-empty"><i>◇</i><h3>No records here yet</h3><p>Create the first verified record for this module.</p></div>}
function StoryAdmin({storyCounts}:{storyCounts:Array<{status:string;count:number}>}){const total=(s:string)=>storyCounts.find(c=>c.status===s)?.count||0;return <section className="story-admin"><div className="metric-grid"><article><span className="metric-orange">▤</span><div><small>PENDING REVIEW</small><b>{total('pending')}</b><em>Community submissions</em></div></article><article><span className="metric-green">✓</span><div><small>PUBLISHED</small><b>{total('published')}</b><em>Live human stories</em></div></article><article><span>○</span><div><small>HELD</small><b>{total('rejected')}</b><em>Not publicly visible</em></div></article></div><div className="story-admin-cta"><div><small>EDITORIAL WORKFLOW</small><h2>Human story review desk</h2><p>Review full submissions, contributor details and media before publishing.</p></div><a href="/stories/manage">OPEN STORY REVIEW →</a></div></section>}
function SystemHealth({counts}:{counts:Count[]}){return <section className="system-page"><div className="system-hero"><span>ALL SYSTEMS</span><h2>Data infrastructure is ready.</h2><p>One secure database powers every operational module, with media stored separately and every administrative change recorded.</p></div><div className="system-grid">{[['Structured database','Connected','D1'],['Photo & video storage','Connected','R2'],['Administrator access','Protected','AUTH'],['Audit history','Recording','LOG'],['Public operations feed',counts.some(c=>c.status==='published')?'Active':'Awaiting records','API'],['Story submissions','Ready','FORM']].map(([name,status,code])=><article key={name}><i>{code}</i><span><b>{name}</b><small>{status}</small></span><em>✓</em></article>)}</div></section>}
function AdminLoader(){return <div className="admin-loader"><i/><span>Loading secure records…</span></div>}
function EmptyMini({text}:{text:string}){return <div className="empty-mini">{text}</div>}
