import {NextRequest,NextResponse} from 'next/server';
import {ensureSchema,isAdmin,OperationRow} from '@/db';

export const dynamic='force-dynamic';
const types=new Set(['request','offer','reunification','map','update','organization','alert']);
const statuses=new Set(['draft','pending','verified','published','resolved','archived']);
const priorities=new Set(['low','medium','high','critical']);
const clean=(value:unknown,max=500)=>String(value??'').trim().slice(0,max);
function actor(request:NextRequest){const email=request.headers.get('oai-authenticated-user-email')||(process.env.NODE_ENV==='development'?'seedy@sites.test':null);return isAdmin(email)?email:null}

export async function GET(request:NextRequest){const email=actor(request);if(!email)return NextResponse.json({error:'Not authorized'},{status:403});const DB=await ensureSchema();const type=request.nextUrl.searchParams.get('type'),status=request.nextUrl.searchParams.get('status'),q=clean(request.nextUrl.searchParams.get('q'),100);const clauses:string[]=[];const values:string[]=[];if(type&&types.has(type)){clauses.push('record_type = ?');values.push(type)}if(status&&statuses.has(status)){clauses.push('status = ?');values.push(status)}if(q){clauses.push('(title LIKE ? OR description LIKE ? OR location LIKE ?)');values.push(`%${q}%`,`%${q}%`,`%${q}%`)}const where=clauses.length?` WHERE ${clauses.join(' AND ')}`:'';const records=await DB.prepare(`SELECT * FROM operations_records${where} ORDER BY CASE priority WHEN 'critical' THEN 1 WHEN 'high' THEN 2 WHEN 'medium' THEN 3 ELSE 4 END, updated_at DESC LIMIT 500`).bind(...values).all<OperationRow>();const counts=await DB.prepare("SELECT record_type, status, COUNT(*) count FROM operations_records GROUP BY record_type, status").all<{record_type:string;status:string;count:number}>();const stories=await DB.prepare("SELECT status, COUNT(*) count FROM stories GROUP BY status").all<{status:string;count:number}>();const recent=await DB.prepare('SELECT * FROM audit_log ORDER BY created_at DESC LIMIT 12').all<{id:string;record_id:string;action:string;actor_email:string;created_at:string}>();return NextResponse.json({records:records.results,counts:counts.results,storyCounts:stories.results,recent:recent.results})}

export async function POST(request:NextRequest){const email=actor(request);if(!email)return NextResponse.json({error:'Not authorized'},{status:403});const input=await request.json() as Record<string,unknown>;const recordType=clean(input.record_type,30),title=clean(input.title,160),priority=clean(input.priority,20)||'medium',status=clean(input.status,20)||'draft';if(!types.has(recordType)||!title||!priorities.has(priority)||!statuses.has(status))return NextResponse.json({error:'Invalid record'},{status:400});const id=crypto.randomUUID(),now=new Date().toISOString(),DB=await ensureSchema(),publishedAt=status==='published'?now:null;await DB.batch([DB.prepare('INSERT INTO operations_records (id,record_type,title,description,category,location,contact_name,contact_email,contact_phone,priority,status,latitude,longitude,people_count,source,created_by,created_at,updated_at,published_at,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,recordType,title,clean(input.description,6000),clean(input.category,100),clean(input.location,180),clean(input.contact_name,120),clean(input.contact_email,180),clean(input.contact_phone,60),priority,status,input.latitude===null||input.latitude===''?null:Number(input.latitude),input.longitude===null||input.longitude===''?null:Number(input.longitude),Math.max(0,Number(input.people_count)||0),clean(input.source,240),email,now,now,publishedAt,JSON.stringify(input.metadata||{})),DB.prepare('INSERT INTO audit_log (id,record_id,action,actor_email,details_json,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'created',email,JSON.stringify({recordType,status,priority}),now)]);return NextResponse.json({ok:true,id},{status:201})}

export async function PATCH(request:NextRequest){const email=actor(request);if(!email)return NextResponse.json({error:'Not authorized'},{status:403});const input=await request.json() as Record<string,unknown>,id=clean(input.id,80),status=clean(input.status,20),priority=clean(input.priority,20);if(!id||status&&!statuses.has(status)||priority&&!priorities.has(priority))return NextResponse.json({error:'Invalid update'},{status:400});const DB=await ensureSchema(),existing=await DB.prepare('SELECT * FROM operations_records WHERE id = ?').bind(id).first<OperationRow>();if(!existing)return NextResponse.json({error:'Not found'},{status:404});const nextStatus=status||existing.status,nextPriority=priority||existing.priority,now=new Date().toISOString(),publishedAt=nextStatus==='published'?(existing.published_at||now):null;await DB.batch([DB.prepare('UPDATE operations_records SET status = ?, priority = ?, updated_at = ?, published_at = ? WHERE id = ?').bind(nextStatus,nextPriority,now,publishedAt,id),DB.prepare('INSERT INTO audit_log (id,record_id,action,actor_email,details_json,created_at) VALUES (?,?,?,?,?,?)').bind(crypto.randomUUID(),id,'updated',email,JSON.stringify({from:{status:existing.status,priority:existing.priority},to:{status:nextStatus,priority:nextPriority}}),now)]);return NextResponse.json({ok:true})}
