const needItems = [['✚','Medical Assistance'],['♜','Food & Water'],['⌂','Shelter'],['♧','Clothing'],['♨','Rescue / Evacuation'],['⊕','Other Needs']];
const helpItems = [['♙','Volunteer On-Site'],['♧','Donate Funds'],['♜','Donate Supplies'],['♧','Share Skills'],['▣','Transport / Logistics'],['◇','Other Ways to Help']];
const mapPins = [['medical',14,14],['shelter',27,31],['medical',34,27],['food',46,46],['shelter',59,25],['rescue',73,35],['medical',82,58],['food',88,73],['shelter',43,75],['medical',51,62],['shelter',68,68],['food',31,72]] as const;

function ActionPanel({kind}:{kind:'need'|'help'}) {
  const isNeed=kind==='need'; const items=isNeed?needItems:helpItems;
  return <section className={`panel action-panel ${kind}`}><h2><span>{isNeed?'♧':'♡'}</span>{isNeed?'I NEED HELP':'I CAN HELP'}</h2><p>{isNeed?'Tell us what you need and where you are.':'Choose how you can contribute.'}</p><div className="action-list">{items.map(([icon,label])=><button key={label}><b>{icon}</b>{label}</button>)}</div><button className="primary-action">{isNeed?'SUBMIT REQUEST':'OFFER HELP'}</button></section>;
}

export default function Home(){return <main>
  <nav className="topbar"><a className="brand" href="#top"><span className="brand-mark">♡</span><span><strong>NEPAL RELIEF CONNECT</strong><small>CODES WITH CONSCIENCE</small></span></a><div className="navlinks"><a href="#top">HOME</a><a href="#needs">I NEED HELP</a><a href="#help">I CAN HELP</a><a href="#resources">RESOURCES</a><a href="#updates">UPDATES</a><a href="#about">ABOUT</a></div><div className="nav-actions"><span className="online"><i/> STARLINK ONLINE</span><button>EN⌄</button><button className="alert">♧ EMERGENCY ALERTS</button></div></nav>
  <header className="hero" id="top"><div className="hero-copy"><div className="eyebrow">DISASTER RESPONSE · NEPAL</div><h1>TOGETHER FOR NEPAL <span>🇳🇵</span></h1><h3>Connect. Coordinate. Save Lives.</h3><p>A real-time platform connecting people in need<br/>with people who can help.</p><div className="hero-buttons"><a href="#needs" className="red-button">♧ <span><b>I NEED HELP</b><small>Request Assistance</small></span></a><a href="#help" className="green-button">♡ <span><b>I CAN HELP</b><small>Offer Support</small></span></a></div></div>
  <section className="situation" id="updates"><div className="situation-head"><span><b>LIVE SITUATION UPDATE</b><small>AUG 29, 2026 · 4:02 PM NPT</small></span><em>● LIVE</em></div><div className="stats"><div><span className="red">♧</span><small>People in Need</small><b>12,846</b></div><div><span className="blue">⌖</span><small>Active Requests</small><b>2,153</b></div><div><span className="green">✓</span><small>Help Provided</small><b>7,298</b></div><div><span className="orange">♙</span><small>Volunteers</small><b>4,672</b></div></div><p><b>Latest update:</b> Monsoon flooding continues in multiple regions. Roads blocked in remote areas. Relief efforts ongoing.</p><a href="#resources">View Full Situation Report →</a></section><div className="helpline"><b>Emergency?</b> Call Local Helpline: 1144 <i/> Police: 100 <i/> Ambulance: 102 <i/> Fire: 101</div></header>
  <div className="dashboard"><div className="top-grid"><div id="needs"><ActionPanel kind="need"/></div><div id="help"><ActionPanel kind="help"/></div>
  <section className="panel map-panel" id="resources"><h2>♧ LIVE NEEDS MAP</h2><div className="map"><span className="city kathmandu">Kathmandu</span><span className="city pokhara">Pokhara</span><span className="city lalitpur">Lalitpur</span><span className="river"/>{mapPins.map(([type,left,top],i)=><i key={i} className={`pin ${type}`} style={{left:`${left}%`,top:`${top}%`}}>{type==='medical'?'✚':type==='food'?'⌂':type==='rescue'?'♟':'♜'}</i>)}<div className="zoom">+<hr/>−</div></div><div className="legend"><span className="medical">● Medical</span><span className="food">● Food/Water</span><span className="shelter">● Shelter</span><span className="rescue">● Rescue</span><span className="other">● Other</span></div></section>
  <section className="panel family-panel"><h2>♟ FAMILY REUNIFICATION</h2><div className="tabs"><b>I&apos;M LOOKING FOR SOMEONE</b><span>I WANT TO BE FOUND</span></div><label>Name of Missing Person<input placeholder="Enter full name"/></label><label>Last Seen Location<input placeholder="e.g. Bhaktapur, Kathmandu"/></label><label>Any other details<input placeholder="Age, clothing, contact, etc."/></label><button>SUBMIT SEARCH</button></section></div>
  <div className="bottom-grid"><section className="panel feed-panel"><h2>▣ REAL-TIME FEED</h2><div className="feed-row need-row"><b>♧ NEED</b><span><strong>Urgent medical help needed in Bhaktapur!</strong><small>Severe injuries, no access to hospital.</small></span><time>2 min ago<small>Bhaktapur</small></time></div><div className="feed-row offer-row"><b>⌖ OFFER</b><span><strong>We have tents and blankets ready to deliver.</strong><small>Heading to Gorkha area.</small></span><time>5 min ago<small>Gorkha</small></time></div><div className="feed-row info-row"><b>⊙ INFO</b><span><strong>Road to Sindhuli is blocked near Melamchi.</strong><small>Use alternate route via Old Araniko.</small></span><time>8 min ago<small>Sindhuli</small></time></div><div className="feed-row offer-row"><b>⌖ OFFER</b><span><strong>Medical team available in Kathmandu.</strong></span><time>12 min ago</time></div></section>
  <section className="panel how-panel"><h2>HOW IT WORKS</h2><div className="steps"><div><i>▤</i><b>1. Post Need</b><small>Tell us what<br/>you need</small></div><em>→</em><div><i>♙</i><b>2. Get Connected</b><small>We match you<br/>with helpers</small></div><em>→</em><div><i>✓</i><b>3. Help Arrives</b><small>Relief reaches<br/>you faster</small></div></div></section>
  <section className="panel org-panel"><h2>VERIFIED ORGANIZATIONS</h2>{[['✚','Red Cross Nepal','Medical & Relief'],['◉','UN OCHA','Coordination'],['♜','Hami Nepal','Volunteers'],['▦','Local Community Groups','On-Ground Support']].map(([icon,name,type])=><div key={name}><i>{icon}</i><span><b>{name}</b><small>{type}</small></span><em>✓</em></div>)}</section>
  <section className="panel share-panel"><h2>CONNECT & SHARE</h2><p>Help spread the word and connect us all.</p><div className="socials"><i>f</i><i>♥</i><i>☏</i><i>◎</i><i>✉</i></div><div className="broadcast"><b>◉</b><span>Auto-broadcasting updates to all networks<br/>every 2 minutes</span></div></section></div></div>
  <footer id="about"><div><b>⌁</b><span><strong>Runs on Starlink</strong><small>Always connected. Always on.</small></span></div><div><b>◇</b><span><strong>Codes with Conscience</strong><small>Technology with humanity at heart.</small></span></div><div><b>♙</b><span><strong>Built by volunteers, for humanity.</strong><small>Open source. Open heart.</small></span></div></footer>
</main>}
